import {asset} from './preview.mjs';
import React,{useRef,useState} from 'react';
import {Camera,Plus,Trash,ArrowClockwise} from '@phosphor-icons/react';
export default function AddPiece({usualSize,onAdd}){
 const [photo,setPhoto]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const input=useRef(null),revision=useRef(0);
 async function choose(file){const current=++revision.current;setError('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5e6){setError('Choose a JPG, PNG or WebP smaller than 5 MB.');if(input.current)input.current.value='';return}setBusy(true);try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('This photo could not be read. Please try another.'));reader.readAsDataURL(file)});await new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=()=>reject(Error('This file is not a readable image.'));img.src=data});if(current===revision.current)setPhoto(data)}catch(e){if(current===revision.current)setError(e.message)}finally{if(current===revision.current)setBusy(false)}}
 function remove(){revision.current++;setPhoto('');setBusy(false);setError('');input.current.value=''}
 return <div className="add-piece"><p className="eyebrow">YOUR CLOSET, ONE PIECE AT A TIME</p><h2>Add a favorite.</h2><p>Take a clear photo of your piece, then give it a name.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=f.get('name').trim();if(!name){setError('Give your piece a name.');return}onAdd({name,brand:f.get('brand').trim()||'My wardrobe',category:f.get('category'),price:f.get('price')===''?null:Number(f.get('price')),currency:'USD',color:'Your piece',sizes:[],size:f.get('size').trim(),image:photo||asset('assets/piece-placeholder.svg')})}}><input ref={input} className="sr-only" aria-label="Choose garment photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0])}/>{photo?<><div className="added-photo-preview"><img src={photo} alt="Your selected garment photo"/></div><div className="button-row"><button type="button" className="btn" onClick={()=>input.current.click()} disabled={busy}><ArrowClockwise/> Change photo</button><button type="button" className="btn" onClick={remove}><Trash/> Remove photo</button></div></>:<button type="button" className="photo-input" onClick={()=>input.current.click()} disabled={busy}><Camera size={30}/><span>{busy?'Reading photo…':'Add a photo'}</span><small>JPG, PNG or WebP · up to 5 MB</small></button>}{error&&<p role="alert" className="notice">{error}</p>}<label>Piece name<input name="name" placeholder="My favorite navy blazer" required maxLength={120}/></label><div className="form-grid"><label>Brand<input name="brand" placeholder="Optional" maxLength={50}/></label><label>Category<select name="category">{['Tops','Bottoms','Dresses','Layers','Shoes','Bags','Accessories'].map(x=><option key={x}>{x}</option>)}</select></label><label>Size<input name="size" defaultValue={usualSize} maxLength={15}/></label><label>Purchase price (USD)<input type="number" min="0" max="1000000" name="price" placeholder="Optional"/></label></div><p className="caption">Your garment photo is saved in this browser only. Adding a piece does not automatically prepare it for virtual try-on.</p><button className="btn primary" type="submit" disabled={busy}>Add to my closet <Plus/></button></form></div>
}
