import React,{useState} from 'react';
import {Plus,X,Check,MagnifyingGlass,CoatHanger} from '@phosphor-icons/react';
import {COMPARE_LIMIT,comparisonEntries,pieceSource,lookSource} from './wardrobeSelections.mjs';
import './wardrobe-selection.css';
const money=(n,currency)=>n==null?'Price unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:currency||'USD',maximumFractionDigits:0}).format(n);
function LookImage({entry}){
 const [failed,setFailed]=useState(null);
 return <div className={'comparison-visual '+(entry.kind==='look'?'outfit-visual':'')}>{entry.preview&&failed!==entry.preview?<img src={entry.preview} alt={entry.name} onError={()=>setFailed(entry.preview)}/>:entry.pieces.slice(0,4).map(p=><img key={p.id} src={p.image} alt={p.name}/>)}</div>;
}
export default function CompareStudio({pieces,looks,owned,saved,selection,onToggle,onClear,onStyle}){
 const [adding,setAdding]=useState(!selection.length),[source,setSource]=useState('All'),[search,setSearch]=useState('');
 const entries=comparisonEntries(pieces,looks),selected=selection.map(key=>entries.find(e=>e.key===key)).filter(Boolean),full=selection.length>=COMPARE_LIMIT;
 const results=entries.filter(e=>(source==='All'||source==='Saved looks'&&e.kind==='look'||source==='I own'&&e.pieces.every(p=>owned.some(o=>o.id===p.id))||source==='Want to buy'&&e.pieces.some(p=>saved.includes(p.id)&&!owned.some(o=>o.id===p.id))||source==='Shop'&&e.kind==='piece'&&!owned.some(o=>o.id===e.id))&&`${e.name} ${e.brand||''} ${e.pieces.map(p=>p.brand+' '+p.name).join(' ')}`.toLowerCase().includes(search.toLowerCase().trim()));
 return <div className="compare-studio"><p className="eyebrow">A LITTLE PERSPECTIVE</p><h2>Consider them together.</h2><p>Compare up to four pieces or saved looks, from your closet and the shop.</p><div className="comparison-toolbar"><span role="status">{selected.length} of {COMPARE_LIMIT} selected</span><div className="button-row">{selection.length>0&&<button className="small-link" onClick={onClear}>Clear comparison</button>}<button className="btn" aria-expanded={adding} aria-controls="compare-picker" onClick={()=>setAdding(!adding)}>{adding?<X/>:<Plus/>}{adding?'Hide choices':'Add a look'}</button></div></div>
 <div className="comparison-grid">{selected.map(e=><article className="comparison-piece" key={e.key}><LookImage entry={e}/><span className="ownership-label">{e.kind==='look'?lookSource(e.pieces.map(p=>p.id),owned):pieceSource(e,owned,saved)}</span><p className="eyebrow">{e.kind==='look'?`Saved look · ${e.pieces.length} ${e.pieces.length===1?'piece':'pieces'}`:e.brand}</p><h3>{e.name}</h3><p>{e.kind==='look'?'Pieces total · ':''}{money(e.price,e.currency)}</p><button className="btn" onClick={()=>onStyle(e)}><CoatHanger/>{e.kind==='look'?'Edit this look':'Style this piece'}</button><button className="small-link" aria-label={'Remove '+e.name+' from comparison'} onClick={()=>onToggle(e.key)}>Remove</button></article>)}{Array.from({length:Math.max(0,COMPARE_LIMIT-selected.length)},(_,i)=><button className="comparison-slot" key={'slot-'+i} onClick={()=>setAdding(true)}><Plus/><strong>Add a look</strong><span>Your closet, wishlist or shop</span></button>)}</div>
 {adding&&<section className="selection-browser" id="compare-picker" aria-label="Add to comparison"><div className="selection-heading"><h3>What would you like to compare?</h3><p>{full?'Four selected. Remove one above to make room.':'Choose a piece or a complete saved look.'}</p></div><div className="selection-sources" role="group" aria-label="Comparison source">{['All','Saved looks','I own','Want to buy','Shop'].map(s=><button key={s} aria-pressed={source===s} onClick={()=>setSource(s)}>{s}</button>)}</div><label className="selection-search"><MagnifyingGlass/><input aria-label="Search comparison choices" placeholder="Search pieces, looks or brands" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="selection-results">{results.map(e=>{const active=selection.includes(e.key);return <button className={'selection-choice '+(active?'selected':'')} key={e.key} aria-pressed={active} aria-label={(active?'Remove ':'Add ')+e.name+(active?' from comparison':' to comparison')} disabled={full&&!active} onClick={()=>onToggle(e.key)}><LookImage entry={e}/><span className="selection-choice-copy"><small>{e.kind==='look'?'Saved look':pieceSource(e,owned,saved)}</small><strong>{e.name}</strong><span>{e.kind==='look'?`${e.pieces.length} pieces`:money(e.price,e.currency)}</span></span>{active?<Check/>:<Plus/>}</button>})}</div>{!results.length&&<p className="notice">{search.trim()?'No matches. Try another search.':source==='Saved looks'?'Save an outfit in the styling studio to compare it here.':source==='I own'?'Add or import pieces into your closet to compare them here.':source==='Want to buy'?'Save pieces from Shop to find them here.':'No matches. Try another search.'}</p>}</section>}
 </div>;
}
