import React from 'react';
import {ArrowRight,Check} from '@phosphor-icons/react';
export function TaskGuide({title,steps}){return <details className="task-guide"><summary>How to {title.toLowerCase()}</summary><ol>{steps.map(step=><li key={step}>{step}</li>)}</ol></details>}

export const pageGuides={
 today:{name:'Today',title:'Start with what you need today.',text:'An outfit idea, your closet and a little inspiration. Choose one place to start.',steps:['Open your closet to add clothes you already own.','Build today’s outfit or refresh it for another idea.','Save a look to your planner when you want to wear it.'],action:'Open my closet',destination:'closet'},
 closet:{name:'Closet',title:'Everything you wear, together.',text:'Owned is what you have. Purchases is what you imported. Wishlist is what you might buy.',steps:['Add a piece with a photo and a name, or review sample receipt imports.','Open a garment to view its details and styling options.','Build an outfit and save your favorite combinations.'],action:'Set up my fitting profile',destination:'profile'},
 shop:{name:'Shop',title:'Find it. See it on you. Decide.',text:'Browse real product snapshots. Open any garment for the available fitting and styling tools.',steps:['Narrow the selection by category, brand or search.','Open a garment to try it on, compare pieces or build an outfit.','Shop at the brand opens the retailer’s website to purchase.'],action:'Set up my fitting profile',destination:'profile'},
 discover:{name:'Discover',title:'Turn an idea into your own outfit.',text:'Explore sample creators and your own drafts. Use the pieces in a look as a starting point.',steps:['Follow a creator or filter the feed by the kind of idea you want.','Comment, save inspiration or remix a look with your clothes.','Share a look creates a draft on this device in the public preview.'],action:'Explore trending ideas',destination:'trending'},
 planner:{name:'Plan',title:'A little preparation for your week.',text:'Suggestions use your closet and the available forecast. You stay in control of every day.',steps:['Save an outfit idea for one day or choose Plan my week.','Open a saved day to change its pieces or occasion.','Mark the look worn to keep your wardrobe history up to date.'],action:'Open my closet',destination:'closet'},
 community:{name:'Community',title:'Find your people.',text:'Rooms bring related ideas together. The public preview uses sample rooms and device drafts.',steps:['View a room to see its posts. Join to draft a post in that room.','Share an outfit, a trend board or a how-to.','Comment or remix a look to try the idea yourself.'],action:'Explore the inspiration feed',destination:'discover'},
 messages:{name:'Messages',title:'A second opinion on your style.',text:'These sample conversations help you explore the layout. Nothing is sent to another person here.',steps:['Choose a conversation, or search by name.','Write a reply and save it as a local draft.','Live account messaging is available only in the private signed-in app.'],action:'Explore the community',destination:'community'},
 events:{name:'Events',title:'Take your interests beyond the screen.',text:'Official calendars and sample meetups are labeled so you can tell them apart.',steps:['Choose a city to narrow the events.','Open an event for dates, location and organizer information.','Save a local RSVP or visit the official organizer. This preview does not book attendance.'],action:'Find your fashion circle',destination:'community'},
 stores:{name:'Connected stores',title:'From your purchase to your closet.',text:'Explore partner review stores and manually record what you bought. Retailer accounts are not connected here.',steps:['Open a storefront review to explore its fitting experience.','Choose the exact garment you bought in Record a purchase.','Mark it received to add it to your closet.'],action:'Open my closet',destination:'closet'},
 trending:{name:'Trending',title:'See what inspires you, near or far.',text:'Global and local sample edits illustrate how the style radar will work. Counts are illustrative.',steps:['Switch between Global, Country and Near you.','Choose a country or city to explore a local edit.','Open a piece, save it or build an outfit from the idea.'],action:'Explore the feed',destination:'discover'},
 profile:{name:'Profile',title:'Make the experience yours.',text:'Your photo or Twin and optional measurements prepare your fitting profile.',steps:['Choose your photo or a Twin. Preview it, replace it or remove it.','Save your fitting profile. This does not start a try-on.','Open a garment and choose Try it on when you’re ready. Personal photos clear on reload.'],action:'Explore pieces to try on',destination:'shop'}
};

export function PageHelp({page,onGo,onAll}){
 const guide=pageGuides[page]||pageGuides.today;
 return <div className="page-help"><p className="eyebrow">A LITTLE HELP · {guide.name.toUpperCase()}</p><h2>{guide.title}</h2><p>{guide.text}</p><ol>{guide.steps.map((step,i)=><li key={step}><span>{i+1}</span><p>{step}</p></li>)}</ol><div className="button-row"><button className="btn primary" onClick={()=>onGo(guide.destination)}>{guide.action}<ArrowRight/></button><button className="small-link" onClick={onAll}>Guide to every page<ArrowRight/></button></div><p className="caption"><Check/> Your wardrobe and drafts save in this browser.</p></div>;
}
