import {asset} from './preview.mjs';
import React,{useState} from 'react';
import {Check,Camera,Envelope,CoatHanger,Palette} from '@phosphor-icons/react';
import {rooms} from './rooms.mjs';
export function TaskGuide({title,steps}){return <details className="task-guide"><summary>How to {title.toLowerCase()}</summary><ol>{steps.map(step=><li key={step}>{step}</li>)}</ol></details>}
export function ClosetSetup({profile,room,onFinish}){
 const [step,setStep]=useState(0),[name,setName]=useState(profile.name),[city,setCity]=useState(profile.city),[chosen,setChosen]=useState(room),[choice,setChoice]=useState('sample');
 const labels=['About you','Your room','Your first piece'];
 return <div className="closet-setup"><p className="eyebrow">WELCOME TO SPREEAI</p><h2>Make room for your style.</h2><div className="setup-progress" aria-label="Closet setup progress">{labels.map((label,i)=><span key={label} aria-current={step===i?'step':undefined} className={i<=step?'reached':''}><b>{i<step?<Check/>:i+1}</b>{label}</span>)}</div><form onSubmit={e=>{e.preventDefault();if(step<2)setStep(step+1);else onFinish({name:name.trim(),city:city.trim(),room:chosen,choice})}}>{step===0?<><h3>A little about you.</h3><p>Your city helps us suggest outfits for the weather.</p><label>Your name<input value={name} onChange={e=>setName(e.target.value)} maxLength={40} required autoComplete="given-name"/></label><label>Your city<input value={city} onChange={e=>setCity(e.target.value)} maxLength={60} required autoComplete="address-level2"/></label><p className="caption">No location tracking. You can change these later.</p></>:step===1?<><h3>Choose your room.</h3><p>A starting point you can customize anytime.</p><div className="setup-rooms">{rooms.map(r=><button key={r.id} type="button" aria-pressed={chosen===r.id} onClick={()=>setChosen(r.id)}><img src={asset('assets/'+r.image)} alt=""/><span>{r.title}{chosen===r.id&&<Check/>}</span></button>)}</div></>:<><h3>Start with one favorite.</h3><p>You can add more pieces whenever you like.</p><div className="setup-choices">{[['add',Camera,'Add a piece','Upload a garment photo and a few details.'],['gmail',Envelope,'Find my purchases','Connect Gmail and review receipt matches.'],['sample',CoatHanger,'Explore the sample closet','Try the experience before adding your clothes.']].map(([id,Icon,title,description])=><button key={id} type="button" aria-pressed={choice===id} onClick={()=>setChoice(id)}><Icon/><span><strong>{title}</strong><small>{description}</small></span>{choice===id&&<Check/>}</button>)}</div><p className="caption">Your sample wardrobe is clearly labeled. It does not represent your actual purchases.</p></>}<div className="setup-bottom">{step>0?<button type="button" className="btn" onClick={()=>setStep(step-1)}>Back</button>:<span/>}<button className="btn primary" type="submit">{step===2?'Open my closet':'Continue'}</button></div></form></div>
}
