const sessions=new Map(),inflight=new Map();
export function fittingConfig(p){return p.partnerId?{base:'https://api.stage.spreeai.com',partner:p.partnerId}:{base:'https://api.dev.spreeai.com',partner:'demo-site'}}
const wait=(ms,signal)=>new Promise((resolve,reject)=>{if(signal?.aborted){reject(new DOMException('Cancelled','AbortError'));return}const t=setTimeout(()=>{signal?.removeEventListener('abort',abort);resolve()},ms);function abort(){clearTimeout(t);reject(new DOMException('Cancelled','AbortError'))}signal?.addEventListener('abort',abort,{once:true})});
async function raw(config,path,body,token,signal){const r=await fetch(config.base+path,{method:body===undefined?'GET':'POST',headers:{...(body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(30000)]):AbortSignal.timeout(30000)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.errors?.[0]?.message||data?.message||`Try-on service unavailable (${r.status}). Please try again.`);return data}
async function session(config){const key=config.base+'/'+config.partner,s=sessions.get(key);if(s?.expiresAt>Date.now()+60000)return s;if(!inflight.has(key))inflight.set(key,raw(config,s?.refresh_token?'/v1/auth/refresh':'/v1/user/guest',s?.refresh_token?{refresh_token:s.refresh_token,partner_id:config.partner}:{partner_id:config.partner,language:'en'}).then(d=>{if(!d.access_token)throw Error('Unable to start a fitting session.');const next={...d,expiresAt:Date.now()+Number(d.expires_in||1800)*1000};sessions.set(key,next);return next}).finally(()=>inflight.delete(key)));return inflight.get(key)}
export async function fittingRequest(p,path,body,signal){const config=fittingConfig(p),s=await session(config);return raw(config,path,body,s.access_token,signal)}
export async function loadTwins(p,signal){const {partner}=fittingConfig(p);const data=await fittingRequest(p,'/v1/avatars?partnerID='+encodeURIComponent(partner)+'&inheritpartner=true&inheritdefault=true',undefined,signal);return data.avatars||[]}
export async function renderTwin(p,twin,signal,onProgress=()=>{},view='front',size,baseSize){if(!p.garmentId||!twin?.id)throw Error('Choose a prepared garment and a Twin first.');onProgress('Preparing your look…');const job=await fittingRequest(p,`/${view==='back'||size?'v3.1':'v3'}/store-experience/tryon`,{garment_set:{garments:[...(p.garmentIds||[p.garmentId]).map(garment_id=>({garment_id}))]},partner_id:fittingConfig(p).partner,image_id:twin.id,source:'web-sdk',no_remove_background:false,...(view==='back'?{view}: {}),...(size&&baseSize?{size,base_size:baseSize}:{})},signal);if(!job.request_id)throw Error('Try-on did not return a request.');const start=Date.now();while(Date.now()-start<180000){if(signal.aborted)throw new DOMException('Cancelled','AbortError');const data=await fittingRequest(p,'/v1/user-assets/tryon/'+encodeURIComponent(job.request_id),undefined,signal);if(data.status==='FAILED')throw Error(data.detail||'This item could not be rendered. Please try another Twin or retry later.');if(data.status==='COMPLETE'){if(!data.image?.url?.startsWith('https://'))throw Error('The service returned no preview image.');return {...data,twinName:twin.name}}onProgress('Creating your preview. This can take a little time.');await wait(2000,signal)}throw Error('This render is taking longer than expected. Please retry later.')}
export async function uploadPhoto(p,file,signal){if(!['image/jpeg','image/png','image/webp'].includes(file?.type)||file.size>10*1024*1024)throw Error('Choose a JPG, PNG or WebP photo under 10 MB.');const form=new FormData();form.append('user_image',file);form.append('source','web-sdk');form.append('is_uploaded','true');const d=await fittingRequest(p,'/v2/store-experience/user-images',form,signal);if(!d.id||!d.url?.startsWith('https://'))throw Error('The photo service returned an incomplete result.');return {...d,name:'You',kind:'photo'}}
export async function recommendSize(p,identity,signal){if(!identity.height||!identity.weight)throw Error('Add height and weight for size guidance.');if(p.sizingReady===false||['Bags','Shoes','Accessories'].includes(p.category))throw Error('Personalized size guidance is unavailable for this item. Use the retailer size guide.');const job=await fittingRequest(p,'/v2/store-experience/sizing',{garment_id:p.garmentId,height_centimeters:identity.height,weight_kilograms:identity.weight,body_type:identity.bodyType,source:'web-sdk'},signal);if(!job.request_id)throw Error('No sizing request was returned.');const start=Date.now();while(Date.now()-start<180000){const d=await fittingRequest(p,'/v1/user-assets/sizing/'+encodeURIComponent(job.request_id),undefined,signal);if(['FAILED','FAILURE','ERROR'].includes(String(d.status||d.result).toUpperCase()))throw Error('The size service could not recommend a size for this item.');if(d.sizing?.size)return d.sizing;await wait(2000,signal)}throw Error('Size guidance is taking longer than expected. Please retry later.')}
export async function renderVideo(p,front,back,signal,onProgress=()=>{}){onProgress('Creating your video preview…');let d=await fittingRequest(p,'/v3.1/store-experience/tryon/turn',{front_image_url:front,back_image_url:back,direction:'to_back'},signal);const start=Date.now();while(d.status!=='ready'){if(d.status==='failed')throw Error('Video try-on is unavailable for this look.');if(!d.turn_id||Date.now()-start>240000)throw Error('Video try-on is taking longer than expected.');await wait(2000,signal);d=await fittingRequest(p,'/v3.1/store-experience/tryon/turn/'+encodeURIComponent(d.turn_id),undefined,signal)}if(!d.video_url?.startsWith('https://'))throw Error('The video service returned no playable preview.');return d.video_url}
export function fittingError(message){if(/no back view|back_flat/i.test(message))return 'Back try-on is unavailable for this piece because a back image has not been prepared. Your front preview is still available in On you.';if(/failed processing|no usable flat|not available|not found|garment.*(QA|available|complete)|invalid garment/i.test(message))return 'This piece is still being prepared for try-on. Please explore another prepared piece.';return message}
