export const GMAIL_SCOPE='https://www.googleapis.com/auth/gmail.readonly';
let token=null,expiresAt=0,loading;
export function gmailConnected(){return Boolean(token&&Date.now()<expiresAt)}
export function gmailQuery(range='1y',now=new Date()){
 const windows={'1y':1,'2y':2,'5y':5};let date='';if(range!=='all'){if(!windows[range])throw Error('Choose a valid receipt date range.');const from=new Date(now);from.setUTCFullYear(from.getUTCFullYear()-windows[range]);date=' after:'+from.toISOString().slice(0,10).replaceAll('-','/');}
 return '{subject:receipt subject:"order confirmation" subject:"order confirmed" subject:"thank you for your order"} -in:spam -in:trash'+date;
}
export function loadGoogleIdentity(){if(window.google?.accounts?.oauth2)return Promise.resolve();if(!loading)loading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=()=>resolve();script.onerror=()=>{loading=null;reject(Error('Google sign-in could not load. Check your connection and try again.'))};document.head.append(script)});return loading}
export function authorizeGmail(clientId){if(!clientId)throw Error('Gmail connection is awaiting the app’s Google client configuration.');if(!window.google?.accounts?.oauth2)throw Error('Google sign-in is still loading. Please try again.');return new Promise((resolve,reject)=>{const client=window.google.accounts.oauth2.initTokenClient({client_id:clientId,scope:GMAIL_SCOPE,include_granted_scopes:false,callback:r=>{if(r.error||!r.access_token)return reject(Error('Google did not grant receipt access. Your inbox was not imported.'));if(!window.google.accounts.oauth2.hasGrantedAllScopes(r,GMAIL_SCOPE))return reject(Error('Read-only Gmail permission was not granted.'));token=r.access_token;expiresAt=Date.now()+Number(r.expires_in||3600)*1000;resolve()},error_callback:r=>reject(Error(r.type==='popup_closed'?'Google sign-in was closed. No receipts were imported.':'Google sign-in could not open. Allow popups for this app and try again.'))});client.requestAccessToken({prompt:'consent'})})}
export async function disconnectGmail(){if(!token)return;const old=token;token=null;expiresAt=0;await new Promise((resolve,reject)=>window.google.accounts.oauth2.revoke(old,r=>r?.error?reject(Error('Local connection cleared. Revoke access in your Google account if needed.')):resolve()));}
async function googleGet(path,signal){if(!gmailConnected())throw Error('Gmail access expired. Reconnect to continue.');const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/'+path,{headers:{Authorization:'Bearer '+token},signal,referrerPolicy:'no-referrer'});if(response.status===401){token=null;expiresAt=0;throw Error('Gmail access expired. Reconnect to continue.')}if(!response.ok)throw Error(response.status===429?'Google’s request limit was reached. Please try again later.':'Google could not read these receipts. Check consent and API configuration.');return response.json()}
function decoded(data){try{return new TextDecoder().decode(Uint8Array.from(atob((data||'').replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0)))}catch{return ''}}
export function receiptText(payload){let output=[];function walk(p){if(!p)return;if(['text/plain','text/html'].includes(p.mimeType)&&p.body?.data)output.push({type:p.mimeType,text:decoded(p.body.data)});(p.parts||[]).forEach(walk)}walk(payload);const plain=output.filter(p=>p.type==='text/plain').map(p=>p.text);return plain.length?plain.join('\n'):output.map(p=>p.text.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&')).join('\n')}
export function matchReceipt(message,catalog){const headers=message.payload?.headers||[],header=name=>headers.find(h=>h.name.toLowerCase()===name)?.value||'',body=receiptText(message.payload),text=(header('Subject')+'\n'+body).toLowerCase();const matches=catalog.filter(p=>{const name=p.name.toLowerCase().replace(/[^\p{L}\p{N} ]/gu,' ').replace(/\s+/g,' ').trim();const clean=text.replace(/[^\p{L}\p{N} ]/gu,' ').replace(/\s+/g,' ');return name.length>10&&clean.includes(name)});return {id:message.id,date:new Date(Number(message.internalDate)||Date.now()).toISOString().slice(0,10),subject:header('Subject').slice(0,160),sender:header('From').slice(0,160),matches:matches.map(p=>p.id),text:body.slice(0,30000)}}
export async function searchReceipts(range,catalog,{signal,onProgress=()=>{},pageToken}={}){const params=new URLSearchParams({q:gmailQuery(range),maxResults:'30'});if(pageToken)params.set('pageToken',pageToken);const list=await googleGet('messages?'+params,signal),rows=[];for(const [i,m] of (list.messages||[]).entries()){onProgress(`Reviewing receipt ${i+1} of ${list.messages.length}…`);const full=await googleGet('messages/'+encodeURIComponent(m.id)+'?format=full',signal);rows.push(matchReceipt(full,catalog))}return {rows,nextPageToken:list.nextPageToken||'',estimated:list.resultSizeEstimate||rows.length}}
