import React,{useEffect,useRef,useState} from 'react';
import {Camera,Check,Users,MagnifyingGlass,Play,ArrowUUpLeft,CoatHanger,Heart} from '@phosphor-icons/react';
import ScrollRow from './ScrollRow.jsx';
import {loadTwins,uploadPhoto,renderTwin,renderVideo,fittingConfig,fittingError} from './fitting.mjs';
import {photoDataURL,decodeImage} from './fittingProfile.mjs';
import {asset} from './preview.mjs';
const identities=new Map(),previews=new Map();
export function clearInlineIdentity(){identities.clear();previews.clear();}
const context=p=>{const c=fittingConfig(p);return c.base+'/'+c.partner};
export default function InlineTryOn({product,profileIdentity,request,onRequest,onPerspectiveChange,onResult,onActivity,onSave}){
 const remembered=identities.get(context(product));
 const saved=profileIdentity?(remembered?.profileKey===profileIdentity.key?remembered:profileIdentity.kind==='photo'?{...profileIdentity,pendingPhoto:true,profileKey:profileIdentity.key}:null):null;
 const cached=previews.get(product.id);
 const prior=cached?.profileKey===profileIdentity?.key?cached:null;
 const [identityReady,setIdentityReady]=useState(false),[selected,setSelected]=useState(saved),[twins,setTwins]=useState([]),[results,setResults]=useState(prior?.results||{}),[video,setVideo]=useState(prior?.video||''),[view,setView]=useState(prior?.results.front?'onYou':'product'),[photo,setPhoto]=useState(product.image),[picker,setPicker]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[imageError,setImageError]=useState(false),[zoom,setZoom]=useState(false);
 const controller=useRef(null),consumed=useRef(null),mounted=useRef(true),gallery=useRef(null),chooser=useRef(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort()}},[]);
 useEffect(()=>{let active=true;const c=new AbortController();loadTwins(product,c.signal).then(list=>{if(!active)return;setTwins(list);if(profileIdentity?.kind==='twin'){const t=list.find(t=>t.id===profileIdentity.id)||list.find(t=>t.name===profileIdentity.name);setSelected(t?{...t,kind:'twin',profileKey:profileIdentity.key}:null)}else if(profileIdentity?.kind==='photo'){const known=identities.get(context(product));setSelected(known?.profileKey===profileIdentity.key?known:{...profileIdentity,pendingPhoto:true,profileKey:profileIdentity.key})}else setSelected(null);setIdentityReady(true)}).catch(e=>{if(active&&e.name!=='AbortError'){setError(fittingError(e.message));setIdentityReady(true)}});return()=>{active=false;c.abort()}},[product.id,profileIdentity?.key]);
 useEffect(()=>{onActivity?.({busy:busy||!!request&&!identityReady,status,error,selectedName:selected?.name,view,ready:!!results.front})},[busy,status,error,selected?.name,view,results.front,identityReady,request?.id]);
 useEffect(()=>{if(!request)return;setError('');setImageError(false);setZoom(false);setView(request.view==='choose'?'onYou':request.view);setPicker(request.view==='choose'||identityReady&&!selected)},[request?.id]);
 useEffect(()=>{if(request&&request.view!=='choose'&&identityReady)setPicker(!selected)},[request?.id,identityReady,selected]);
 useEffect(()=>{if(!request||request.view==='choose'||consumed.current===request.id||busy||!selected||picker||view!==request.view)return;consumed.current=request.id;run(request.view)},[request?.id,selected,picker,busy,view]);
 useEffect(()=>{if(picker)chooser.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})},[picker]);
 async function job(action){if(controller.current)return;const c=new AbortController();controller.current=c;setBusy(true);setError('');try{await action(c.signal)}catch(e){if(mounted.current&&e.name!=='AbortError'){setError(fittingError(e.message));setStatus('')}}finally{if(controller.current===c){controller.current=null;if(mounted.current)setBusy(false)}}}
 async function run(target){gallery.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});await job(async signal=>{let identity=selected;if(identity.pendingPhoto){setStatus('Uploading your saved photo securely…');identity={...await uploadPhoto(product,identity.file,signal),file:identity.file,url:identity.url,profileKey:identity.profileKey};if(signal.aborted||!mounted.current)return;identities.set(context(product),identity);setSelected(identity)}
  let next={...results};async function render(v){const r=await renderTwin(product,identity,signal,setStatus,v);if(signal.aborted||!mounted.current)throw new DOMException('Closed','AbortError');next[v]=r;setResults({...next});previews.set(product.id,{profileKey:identity.profileKey,results:{...next},video});onResult?.(product.id,r);return r}
  if(target==='video'){const front=next.front||await render('front'),back=next.back||await render('back');const url=await renderVideo(product,front.image.url,back.image.url,signal,setStatus);if(signal.aborted||!mounted.current)return;setVideo(url);previews.set(product.id,{profileKey:identity.profileKey,results:next,video:url})}else await render(target==='back'?'back':'front');setStatus('Your preview is ready.');
 })}
 async function choose(t){await job(async()=>{const identity={kind:'twin',key:crypto.randomUUID(),id:t.id,name:t.name,url:t.url};await onPerspectiveChange(identity);if(!mounted.current)return;setSelected({...identity,profileKey:identity.key});setResults({});setVideo('');setPicker(false);setStatus('Your Twin is ready.')})}
 async function readPhoto(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;await job(async signal=>{const url=await photoDataURL(file);await decodeImage(url,signal);const identity={kind:'photo',key:crypto.randomUUID(),name:'You',url,file};await onPerspectiveChange(identity);if(!mounted.current)return;setSelected({...identity,pendingPhoto:true,profileKey:identity.key});setResults({});setVideo('');setPicker(false);setStatus('Your photo is ready.')})}
 function selectView(next){if(busy)return;setImageError(false);setZoom(false);setView(next);if(['onYou','back','video'].includes(next)&&!(next==='video'?video:results[next==='back'?'back':'front']))onRequest(next)}
 const image=view==='product'?photo:view==='model'?product.model:view==='back'?results.back?.image.url:results.front?.image.url;
 const labels=[['product','Product',product.image],['model','On model',product.model],['onYou','On you',results.front?.image.url],['back','Back view',results.back?.image.url],['video','Video try-on',video?results.front?.image.url:null]];
 return <div className="inline-tryon"><div ref={gallery} className={'detail-photo inline-preview-photo '+(zoom?'zoomed':'')}>
  {view==='video'&&video?<video controls playsInline src={video} poster={results.front?.image.url}/>:image&&!imageError?<img src={image} alt={view==='product'?product.name:view==='model'?'Retailer model wearing '+product.name:(selected?.name||'Personal')+' wearing '+product.name} onError={()=>setImageError(true)}/>:<div className="inline-preview-empty"><Users/><h3>{picker?'Make this look yours.':'Your personal preview.'}</h3><p>{imageError?'This image could not load. Retry your preview.':picker?'Choose your saved photo or a Twin below. Your preview will start here.':'Use Try it on to see this piece on your photo or Twin.'}</p></div>}
  {(busy||!!request&&!identityReady)&&<div className="render-overlay"><img src={asset('assets/spreeai.svg')} alt="SPREEAI"/><span className="render-progress"/><p role="status">{busy?status:'Getting your fitting profile ready…'}</p><small>You can close this window at any time.</small></div>}
  {image&&!busy&&view!=='video'&&<button className="icon-button" aria-label={zoom?'Show full image':'Zoom product image'} onClick={()=>setZoom(!zoom)}><MagnifyingGlass/></button>}
 </div>
 {view==='product'&&product.images?.length>1&&<div className="product-image-gallery">{product.images.map((url,i)=><button key={url} aria-label={'Product photo '+(i+1)} aria-pressed={photo===url} onClick={()=>setPhoto(url)}><img src={url} alt=""/></button>)}</div>}
 {view!=='product'&&view!=='model'&&<p role="status" className="caption inline-preview-credit">{busy?'Creating your preview…':selected?.name?'On '+selected.name:'Choose your perspective'} · AI-generated preview · Appearance and fit may vary.</p>}
 {results.front&&!busy&&<button className="small-link inline-save-preview" onClick={()=>onSave?.(product,view==='back'&&results.back?results.back:results.front)}><Heart/> Save this preview</button>}
 <ScrollRow className="preview-tabs fitting-thumbnails" label="previews" disabled={busy}>{labels.map(([id,label,thumb])=><button key={id} aria-pressed={view===id} className={view===id?'active':''} disabled={busy||id==='model'&&!product.model} onClick={()=>selectView(id)}>{thumb?<img src={thumb} alt={label+' thumbnail'}/>:<span className="preview-feature">{id==='video'?<Play/>:id==='back'?<ArrowUUpLeft/>:id==='model'?<CoatHanger/>:<Users/>}</span>}<strong>{label}</strong></button>)}</ScrollRow>
 {picker&&<section ref={chooser} className="inline-perspective-picker" aria-label="Choose your fitting perspective"><h3>Your photo or a Twin.</h3><p>Choose once. Your perspective stays ready for every garment.</p><label className="photo-input fitting-photo-input"><Camera/> Add my photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={readPhoto}/></label><p className="caption">Your adult full-length photo stays on this device and is sent securely to SPREEAI when you try this piece on.</p><div className="twin-options">{twins.map(t=><button key={t.id} aria-pressed={selected?.id===t.id} disabled={busy} onClick={()=>choose(t)}><img src={t.url} alt=""/><span>{t.name}</span>{selected?.id===t.id&&<Check/>}</button>)}</div></section>}
 {error&&<p role="alert" className="notice">{error}</p>}
 </div>
}
