import React,{useState} from 'react';
import {Check,MagnifyingGlass,Plus} from '@phosphor-icons/react';
import {pieceSource} from './wardrobeSelections.mjs';
import './wardrobe-selection.css';
export default function OutfitPicker({pieces,owned,saved=[],outfit,onToggle}){
 const [search,setSearch]=useState(''),[source,setSource]=useState('All pieces');
 const results=pieces.filter(p=>(source==='All pieces'||source==='I own'&&owned.some(o=>o.id===p.id)||source==='Want to buy'&&saved.includes(p.id)&&!owned.some(o=>o.id===p.id)||source==='Shop'&&!owned.some(o=>o.id===p.id))&&`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(search.toLowerCase().trim()));
 return <section className="selection-browser outfit-additions" aria-label="Choose outfit pieces"><div className="selection-heading"><h3>Add to your look.</h3><p>Mix what you own with pieces you want to buy. Adding a shopping piece here doesn’t mark it as owned.</p></div><div className="selection-sources" role="group" aria-label="Outfit piece source">{['All pieces','I own','Want to buy','Shop'].map(s=><button key={s} aria-pressed={source===s} onClick={()=>setSource(s)}>{s}</button>)}</div><label className="selection-search"><MagnifyingGlass/><input aria-label="Search outfit pieces" placeholder="Find a piece or brand" value={search} onChange={e=>setSearch(e.target.value)}/></label><p className="caption" aria-live="polite">{results.length} {results.length===1?'piece':'pieces'} · Select to add; select again to remove.</p><div className="selection-results">{results.map(p=><button key={p.id} className={'selection-choice '+(outfit.includes(p.id)?'selected':'')} aria-label={(outfit.includes(p.id)?'Remove ':'Add ')+p.name+(outfit.includes(p.id)?' from outfit':' to outfit')} aria-pressed={outfit.includes(p.id)} onClick={()=>onToggle(p.id)}><img loading="lazy" src={p.image} alt=""/><span className="selection-choice-copy"><small>{pieceSource(p,owned,saved)}</small><strong>{p.name}</strong><span>{p.brand}</span></span>{outfit.includes(p.id)?<Check/>:<Plus/>}</button>)}</div>{!results.length&&<p className="notice">{search.trim()?'No matching pieces. Try another search.':source==='I own'?'Add clothes to your closet to see them here.':source==='Want to buy'?'Save pieces from Shop to collect them here.':'No matching pieces. Try another search.'}</p>}</section>
}
