import React,{useState,useEffect,useRef} from 'react';
import {Camera,Users,Check,Trash} from '@phosphor-icons/react';
import {loadTwins,fittingError} from './fitting.mjs';
import {fitValues,normalizeFit} from './profileFit.mjs';
export default function ProfileFitting({product,profile,identity,onPreview,onSave,onRemove}) {
  const [choice,setChoice]=useState(identity),[mode,setMode]=useState(identity?.kind==='twin'?'twin':'photo'),[twins,setTwins]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[unit,setUnit]=useState(profile.fitUnit||'metric'),[values,setValues]=useState(()=>fitValues(profile.fit,profile.fitUnit||'metric')),[usual,setUsual]=useState(profile.usualSize),[consent,setConsent]=useState(false),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false);
  const readerRef=useRef(null);
  useEffect(()=>{setChoice(identity)},[identity?.key]);
  useEffect(()=>{onPreview?.(choice)},[choice,onPreview]);
  useEffect(()=>()=>onPreview?.(undefined),[onPreview]);
  useEffect(()=>{if(mode!=='twin')return;let active=true;const controller=new AbortController();setLoading(true);setError('');loadTwins(product,controller.signal).then(list=>{if(active)setTwins(list)}).catch(e=>{if(active&&e.name!=='AbortError')setError(fittingError(e.message))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false;controller.abort()}},[mode,product.id]);
  useEffect(()=>()=>readerRef.current?.abort(),[]);
  async function readPhoto(e) {
    const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');setSaved(false);
    if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('Choose a JPG, PNG or WebP photo under 10 MB.');return;}
    readerRef.current?.abort();
    const reader=new FileReader();readerRef.current=reader;
    reader.onerror=()=>setError('This photo could not be opened. Try another file.');
    reader.onload=()=>{const image=new Image();image.onload=()=>{setChoice({kind:'photo',key:crypto.randomUUID(),name:'You',url:reader.result,file});setConsent(false)};image.onerror=()=>setError('This file is not a readable photo.');image.src=reader.result;};
    reader.readAsDataURL(file);
  }
  function units(next) {try{setValues(fitValues(normalizeFit(values,unit),next));setUnit(next);setError('');setSaved(false)}catch(e){setError(e.message)}}
  async function save(e) {e.preventDefault();if(saving)return;setSaving(true);setError('');try{if(choice?.kind==='photo'&&!consent&&choice.key!==identity?.key)throw new Error('Confirm how your photo will be used before saving.');await onSave({identity:choice,fit:normalizeFit(values,unit),fitUnit:unit,usualSize:usual});setSaved(true)}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <section className="profile-fitting" aria-labelledby="profile-fitting-title"><div className="section-heading"><div><p className="eyebrow">YOUR ALWAYS ON PROFILE</p><h2 id="profile-fitting-title">Make every fitting yours.</h2><p>One place for your photo, your Twin and your fit. Ready whenever you open a garment.</p></div></div>
    <form onSubmit={save}><div className="profile-fitting-grid"><div className="profile-perspective"><h3 className="profile-step"><span>01</span> Your perspective</h3><div className="profile-perspective-tabs" aria-label="Choose your fitting perspective"><button type="button" aria-pressed={mode==='photo'} onClick={()=>setMode('photo')}><Camera/> Your photo</button><button type="button" aria-pressed={mode==='twin'} onClick={()=>setMode('twin')}><Users/> Use a Twin</button></div>
      {choice?.url?<div className="profile-fitting-preview"><img src={choice.url} alt={choice.kind==='photo'?'Your selected fitting photo':choice.name+' · selected Twin'}/><div><strong>{choice.kind==='photo'?'Your photo':choice.name}</strong><span>{choice.key!==identity?.key?'Preview · save to use it everywhere':choice.kind==='photo'?'Saved on this device until you change it':'Saved Twin for every fitting'}</span></div></div>:mode==='photo'?<div className="profile-fitting-empty"><div className="profile-photo-symbol"><Camera aria-hidden="true"/></div><div><h3>See it on you.</h3><p>Add a full-length photo. You can preview it before saving.</p></div></div>:null}
      {mode==='photo'?<><label className="profile-upload btn"><Camera/>{choice?.kind==='photo'?'Choose another photo':'Choose my photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={readPhoto}/></label><p className="caption">Use your own adult photo, facing forward, with your full body in frame. JPG, PNG or WebP · up to 10 MB.</p></>:<><p role="status" className="caption">{loading?'Loading available Twins…':'Choose a preset, then save your fitting profile.'}</p><div className="profile-twins">{twins.map(t=><button key={t.id} type="button" aria-pressed={choice?.kind==='twin'&&choice.id===t.id} onClick={()=>{setChoice({kind:'twin',key:crypto.randomUUID(),id:t.id,name:t.name,url:t.url});setSaved(false)}}><img src={t.url} alt="" loading="lazy"/><span>{t.name}</span>{choice?.kind==='twin'&&choice.id===t.id&&<Check aria-hidden="true"/>}</button>)}</div></>}
      {choice&&<button type="button" className="small-link" onClick={async()=>{setSaved(false);try{if(choice.key===identity?.key){await onRemove();setChoice(null)}else setChoice(identity||null)}catch(e){setError(e.message)}}}><Trash/> Remove {choice.kind==='photo'?'my photo':'selected Twin'}</button>}
    </div><div className="profile-measurements"><h3 className="profile-step"><span>02</span> Your fit details</h3><p className="caption">Optional now. Add your measurements for personalized size guidance. Always private.</p><label>Measurement units<select value={unit} onChange={e=>units(e.target.value)}><option value="metric">Centimeters & kilograms</option><option value="imperial">Inches & pounds</option></select></label><div className="form-grid">{[['height','Height',unit==='metric'?'cm':'in'],['weight','Weight',unit==='metric'?'kg':'lb']].map(([key,label,suffix])=><label key={key}>{label} ({suffix})<input type="number" step="any" inputMode="decimal" value={values[key]} onChange={e=>{setValues({...values,[key]:e.target.value});setSaved(false)}} placeholder="Optional"/></label>)}</div><div className="form-grid"><label>Usual clothing size<select value={usual} onChange={e=>{setUsual(e.target.value);setSaved(false)}}>{['XS','S','M','L','XL','XXL','3XL'].map(s=><option key={s}>{s}</option>)}</select></label><label>Sizing profile<select value={values.bodyType} onChange={e=>{setValues({...values,bodyType:e.target.value});setSaved(false)}}><option>Feminine</option><option>Masculine</option></select></label></div><details><summary>Additional measurements · optional</summary><div className="form-grid">{[['bust','Chest / bust'],['waist','Waist'],['hips','Hips']].map(([key,label])=><label key={key}>{label} ({unit==='metric'?'cm':'in'})<input type="number" step="any" inputMode="decimal" value={values[key]} onChange={e=>{setValues({...values,[key]:e.target.value});setSaved(false)}} placeholder="Optional"/></label>)}</div><p className="caption">Keep these for your fit notes. Current live size guidance uses height, weight and sizing profile.</p></details>
    </div></div>{choice?.kind==='photo'&&choice.key!==identity?.key&&<label className="checkbox-label profile-photo-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I understand that my photo is saved on this device until I replace or remove it and is sent securely to SPREEAI when I choose to create a try-on.</label>}
    <div className="profile-fitting-save"><button className="btn primary" type="submit" disabled={saving}><Check/> {saving?'Saving…':'Save fitting profile'}</button><p role="status">{saved?'Saved. Choose a garment and tap Try on when you’re ready.':'Saving prepares your profile. It doesn’t create a try-on.'}</p></div>{error&&<p className="notice" role="alert">{error}</p>}<details className="profile-privacy"><summary>How your fitting profile is saved</summary><p className="caption">Your photo, Twin and fit details are remembered across pages and app reloads on this device. Photos are stored separately from wardrobe exports and sent securely to SPREEAI only when you create a try-on. Clearing browser data removes this saved copy; another device or browser needs its own profile. Replace or remove your photo whenever you choose.</p></details></form>
  </section>;
}
