import React,{useState} from 'react';
import {Check,ArrowRight,MagnifyingGlass,X} from '@phosphor-icons/react';
export const newId=()=>crypto.randomUUID();
export const dateKey=()=>new Date().toLocaleDateString('en-CA');
export const cash=(n,c='USD')=>n===null||n===undefined?'Not recorded':new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(n);
export function B({children,primary=false,...props}){return <button className={'btn '+(primary?'primary':'')} {...props}>{children}</button>}
export function Heading({tag,title,children}){return <div className="tool-heading"><p className="eyebrow">{tag||'MAKE YOUR WARDROBE WORK FOR YOU'}</p><h2>{title}</h2>{children&&<p>{children}</p>}</div>}
export function Field({label,children}){return <label>{label}{children}</label>}
export function EmptyTools({children}){return <p className="tool-empty">{children}</p>}
export function PieceSelect({pieces,value,onChange,label='Choose a piece',allowEmpty=false}){return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)} required>{allowEmpty&&<option value="">Choose a piece</option>}{pieces.map(p=><option key={p.id} value={p.id}>{p.brand} · {p.name}</option>)}</select></Field>}
export function PieceChooser({pieces,selected,onChange,max=12}){const [query,setQuery]=useState('');const filtered=pieces.filter(p=>(p.name+' '+p.brand).toLowerCase().includes(query.toLowerCase()));return <div className="tool-piece-chooser"><label className="tool-search"><MagnifyingGlass/><input aria-label="Find pieces to select" value={query} placeholder="Find a piece" onChange={e=>setQuery(e.target.value)}/></label><p className="caption" aria-live="polite">{selected.length} selected · up to {max}</p><div className="tool-piece-grid">{filtered.map(p=><button type="button" key={p.id} aria-pressed={selected.includes(p.id)} className={selected.includes(p.id)?'selected':''} onClick={()=>onChange(selected.includes(p.id)?selected.filter(id=>id!==p.id):selected.length<max?[...selected,p.id]:selected)}><img loading="lazy" src={p.image} alt=""/><span>{p.name}</span>{selected.includes(p.id)&&<Check/>}</button>)}</div>{!filtered.length&&<EmptyTools>No matching pieces. Add a favorite to Closet, or change your search.</EmptyTools>}</div>}
export function MiniPieces({items,onOpen}){return <div className="tool-mini-pieces">{items.filter(Boolean).map(p=>onOpen?<button key={p.id} type="button" onClick={()=>onOpen(p)} aria-label={'View '+p.name}><img src={p.image} alt={p.name}/></button>:<img key={p.id} src={p.image} alt={p.name}/>)}</div>}
export function ToolCards({cards,onOpen}){return <div className="tool-cards">{cards.map(([kind,Icon,title,text])=><button key={kind} className="tool-card" onClick={()=>onOpen(kind)}><span className="tool-card-icon"><Icon size={25}/></span><span><strong>{title}</strong><small>{text}</small></span><ArrowRight size={19}/></button>)}</div>}
export function downloadText(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Remove({label,onClick}){return <button type="button" className="icon-button" aria-label={label} onClick={onClick}><X/></button>}
