import {generateLook} from './model.mjs';
export const availabilityOptions=['Ready to wear','In the laundry','Lent out','Stored away','Needs repair'];
export const purchaseStatuses=['Ordered','Received','Return requested','Returned','Refund received'];
export const utilityDefaults=()=>({availability:{},purchases:[],listings:[],loans:[],boards:[],offers:[],watches:[],diary:[],fitNotes:[],care:[],trips:[],circles:[],responses:[],wearLogs:[],preferences:{walking:false,coverage:false,softFabrics:false,avoid:'',budget:'',sizeNotes:'',measurements:'',shareSizes:false}});
export function toolsState(value){const base=utilityDefaults();return {...base,...value,preferences:{...base.preferences,...value?.preferences}};}
export function readyPieces(pieces,tools){const uncomfortable=new Set(tools.preferences.learn!==false?tools.diary.filter(d=>d.comfort==='Uncomfortable').flatMap(d=>d.items):[]);return pieces.filter(p=>p.status!=='archived'&&(!tools.availability[p.id]||tools.availability[p.id]==='Ready to wear')&&!uncomfortable.has(p.id)&&(!tools.preferences.walking||!/pump|heel/i.test(p.name))&&(!tools.preferences.avoid||!tools.preferences.avoid.split(',').map(s=>s.trim().toLowerCase()).filter(Boolean).some(s=>(p.name+' '+(p.color||'')).toLowerCase().includes(s))));}
export function deliveredTotal(offer){const values=['price','shipping','tax','fees'].map(k=>offer[k]);if(values.some(v=>v===''||v==null||!Number.isFinite(Number(v))||Number(v)<0))return null;return Math.round(values.reduce((a,v)=>a+Number(v),0)*100)/100;}
export function rankedOffers(offers,{currency,size='',exact=true}={}){return offers.filter(o=>(!currency||o.currency===currency)&&(!size||(o.size||'').toLowerCase()===size.toLowerCase())&&o.stock!=='Out of stock'&&(!exact||o.match==='Exact item')).sort((a,b)=>(deliveredTotal(a)??Infinity)-(deliveredTotal(b)??Infinity));}
export function httpUrl(value){try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password?url.href:''}catch{return ''}}
export function daysUntil(date,now=new Date()){if(!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return null;const current=new Date(now);current.setHours(0,0,0,0);return Math.ceil((new Date(date+'T00:00:00')-current)/86400000);}
export function reminders(tools,now=new Date()){return [...tools.purchases.filter(p=>p.returnBy&&!['Returned','Refund received'].includes(p.status)).map(p=>({kind:'purchases',id:p.id,title:'Return deadline',text:p.name+' · '+(daysUntil(p.returnBy,now)<0?'deadline passed':daysUntil(p.returnBy,now)+' days left'),date:p.returnBy})),...tools.loans.filter(p=>!p.returned).map(p=>({kind:'circulation',id:p.id,title:'Borrowing reminder',text:p.friend+' · '+p.name,date:p.due})),...tools.care.filter(p=>!p.done&&p.date).map(p=>({kind:'care',id:p.id,title:'Care reminder',text:p.task,date:p.date}))].sort((a,b)=>a.date.localeCompare(b.date));}
export function listingText(listing,piece){return [piece.name,piece.brand,'Size: '+(listing.size||piece.size||'Confirm size'),'Condition: '+listing.condition,'Asking price: '+listing.price+' '+listing.currency,listing.description,'Disclosed flaws: '+(listing.flaws||'Review and describe before publishing')].join('\n\n');}
export function beforeBuying(piece,owned){return {similar:owned.filter(p=>p.status!=='archived'&&p.category===piece.category),complements:owned.filter(p=>p.status!=='archived'&&p.category!==piece.category).slice(0,4),owned:owned.some(p=>p.id===piece.id)};}
export function occasionLook(pieces,occasion,tools,rotation=0){const pool=readyPieces(pieces,tools).filter(p=>!tools.preferences.avoid||!tools.preferences.avoid.split(',').map(s=>s.trim().toLowerCase()).filter(Boolean).some(s=>(p.name+' '+(p.color||'')).toLowerCase().includes(s)));return generateLook(pool,occasion,rotation);}
export function createCircle({title,note,mode,items,sizeNotes=''},catalog){return {version:1,title:String(title).slice(0,80),note:String(note).slice(0,400),mode:['Style my closet','Help me choose','Gift wishlist','Coordinate outfits'].includes(mode)?mode:'Style my closet',items:items.slice(0,12).map(p=>({id:catalog.some(c=>c.id===p.id)?p.id:null,name:String(p.name).slice(0,120),brand:String(p.brand||'').slice(0,50),category:String(p.category||'').slice(0,30)})),sizeNotes:String(sizeNotes).slice(0,200)};}
export function encodeCircle(circle){return btoa(unescape(encodeURIComponent(JSON.stringify(circle))));}
export function decodeCircle(code,catalog){try{if(code.length>14000)return null;const c=JSON.parse(decodeURIComponent(escape(atob(code))));if(c.version!==1||typeof c.title!=='string'||c.title.length>80||typeof c.note!=='string'||c.note.length>400||typeof c.sizeNotes!=='string'||c.sizeNotes.length>200||!Array.isArray(c.items)||!c.items.length||c.items.length>12)return null;if(!['Style my closet','Help me choose','Gift wishlist','Coordinate outfits'].includes(c.mode))return null;if(!c.items.every(p=>p&&typeof p.name==='string'&&p.name.length<=120&&typeof p.brand==='string'&&p.brand.length<=50&&typeof p.category==='string'&&p.category.length<=30&&(p.id===null||catalog.some(x=>x.id===p.id))))return null;return c}catch{return null}}
export async function photoData(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5e6)throw Error('Use JPG, PNG or WebP photos smaller than 5 MB each.');const original=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read this photo.'));r.readAsDataURL(file)});const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('This photo could not be opened.'));image.src=original});const scale=Math.min(1,1000/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/webp',.82);}
